defaults:
  - agent: Map_GNN
  - benchmark: maniskill

seed: 0
device: cuda:0

task_name: PickCube-v1
camera_name: base_camera
image_size: 128

project_root: /data2/lirui/StructureMap3D
dataset_dir: ${project_root}/data_new/maniskill/${task_name}_${camera_name}.zarr

dataloader:
  batch_size: 64
  num_workers: 0
  shuffle: True
  drop_last: True
  pin_memory: True

lambda_map: 1
lambda_physical: 1

train:
  clip_grad_value: 1.0
  learning_rate: 1e-4
  num_epochs: 600
  scheduler_instantiate_config:
    _target_: MapPolicy.helpers.pytorch.Optimizers.get_warmup_cosine_annealing_scheduler
    num_warmup_epochs: 20
    num_epochs: ${train.num_epochs}
    warmup_factor: 0.01
    eta_min: 1.0e-6

evaluation:
  num_skip_epochs: 0
  validation_frequency_epochs: 10
  validation_trajs_num: 10
  save_best_model: True

wandb:
  project: MapPolicy
  group: null
  name: Maniskill_${agent.name}_${task_name}_${camera_name}
  notes: maniskill test
  reinit: True
  mode: online

hydra:
  run:
    dir: outputs/maniskill/${agent.name}/${task_name}_${camera_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: maniskill_${agent.name}_${task_name}_${camera_name}
